name:                koak
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/koak-new#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md
# ghc-options:
#   - -Wall
#   - -Wno-name-shadowing
 
dependencies:
  - base >= 4.7 && < 5
  - llvm-hs >= 6
  - llvm-hs-pure
  - llvm-hs-pretty
  - text
  - mtl
  - containers
  - bytestring
  - process
  - optparse-applicative

executables:
  koak:
    source-dirs:      src
    main:             Main.hs
